### ISSUE TITLE
ANSI color escape sequences not formatted windows

### ISSUE THREAD

**Issue by renatoassis** [jest-community/vscode-jest#299] opened 2018-04-09 18:08 UTC
### Environment

1. `node -v`: v8.9.4
2. `npm -v`: 5.8.0
3. Operating system: Microsoft Windows 10 64 bit  1709
4. `Vscode `: 1.22.1
![prtscr capture](https://user-images.githubusercontent.com/1714391/38514526-d6ce57f8-3c07-11e8-9d40-c138b0840376.jpg)

**Comment by hollyleaves** [comment] 2018-04-09 21:59
Duplicate of #279. Use --no-color option for now.

**Closed** 2018-04-09 22:17 UTC
