### ISSUE TITLE
Test state bullets in editor code lens stay in grey "unknown" state instead of turning green

### ISSUE THREAD

**Issue by svdHero** [jest-community/vscode-jest#597] opened 2020-06-17 15:10 UTC
### Environment

1. `node -v`: v14.0.0
1. `npm -v`: 6.14.4
1. `npm ls react-scripts` (I haven’t ejected): react-scripts@3.4.1
1. Operating system: Windows 8.1

### Prerequisite
- are you able to run jest test from command line? Yes
- how do you run your tests from command line? `npm run test` or by letting the Jest extension do it automagically in the background when using VSCode

### Steps to Reproduce

Write any test and run it.

### Relevant Debug Info

The test passes.

### Expected Behavior

The code lens bullet next to the test code turns from grey to green.

### Actual Behavior

The code lens bullet stays grey.

![Jest-Bullets](https://user-images.githubusercontent.com/24250824/84915385-0193ea80-b0bd-11ea-877b-bfe792dbf991.png)

**Comment by Tymek** [comment] 2020-06-28 09:19
extension does runs tests automagically. You can run all tests on startup. Check if you have a setting of `"jest.runAllTestsFirst": true`, otherwise (`false`) it will only run when your files are modified (like `jest -onlyChanged --watch` [cli](https://jestjs.io/docs/en/cli.html#--onlychanged))

**Comment by svdHero** [comment] 2020-06-28 11:30
By "automagically" I did mean that the tests get run when I modify files. But that is not the point of this issue.
The issue - as described - is that, once the tests are run, the test status is NOT reflected in the editor code lens.

**Comment by connectdotz** [comment] 2020-06-28 23:17
do you have a sample repo or turn on the debug mode to see if there is any additional logging info to help diagnose.

**Comment by matteralus** [comment] 2020-06-30 23:34
I am having a similar issue and turned on debugging and git this message '(insert it text here)' failed to find test result: found multiple potential matches, could be caused by duplicate test names or template literals?

In my case the two it's that have the same text are in 2 different describes...I didn't look at the the source code, but is it possible the whole path of the test is not being used as a hash for it's uniqueness, like file->describe1_text->describe2_text->it_text. Maybe another approach would be to use file name and cardinality of describe/it combinations.

**Comment by connectdotz** [comment] 2020-07-02 02:15
@matteralus what you described is a known issue, which should be addressed by v4 (#576). There is an alpha version available now, feel free to give it a try: https://github.com/jest-community/vscode-jest/releases/tag/v4.0.0-alpha.0

**Comment by matteralus** [comment] 2020-07-02 13:58
Thank you @connectdotz! Apologies for getting the issues confused...tried out the alpha and looks like it fixed my problem, thank you and thanks for maintaining this project!

**Closed** 2021-02-26 20:21 UTC

**Comment by timgcarlson** [comment] 2023-01-03 23:33
I'm getting this same issue in my project after updating to 5.1.0. Downgrading to 4.6.0 still works, but on 5.1.0 I get the grey unknown circles next to all of my tests, even though I can still use this extension to run them.

I cannot repro it in a new project, it only appears in my private repo that I cannot link here. I have searched all my tests for duplicate names and there are not any duplicates.

Is there any information that I can provide to help resolve this issue?

**Comment by connectdotz** [comment] 2023-01-04 03:10
The grey circle means the test has not been run. The default `jest.autoRun` is changed in 5.1 so that it will not run all tests upon starting up like in 4.6. I am guessing the tests in your real project are not changed (according to git) so jest watcher did not run tests for them (the default behavior). But in your new project, all tests are "new" so jest watcher will run them and thus you see the test status (not grey).

You can manually run the tests that are grey and see the status updated.

see more detail [in release note](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.1.md#10-autorun-simplification)

**Comment by rgembalik** [comment] 2023-08-29 08:03
@connectdotz It's not necessarily true. I've got a test, which after running turns to previous state immediately after failure. So if it was green, but if the test starts failing it will still show as green. If it was gray, it will be gray on failure. The tree would show as if the file is updated, but the describe/test entries will not update properly.

![image](https://github.com/jest-community/vscode-jest/assets/2618837/89c13d50-7c07-44ad-8d78-87f2187773a6)

![image](https://github.com/jest-community/vscode-jest/assets/2618837/c085db19-a138-48c9-b218-5ed485a883eb)

I've v5.2.3, testing next.js app with typescript.

**Comment by connectdotz** [comment] 2023-08-29 18:04
hmmm... that sounds like a bug. I am not able to reproduce this, probably under certain situation some how the test item did not get updated...? Do you have a sample repo we can reproduce this issue? Feel free to open a new issue, this issue was very old and related to the version no longer valid.

**Comment by rgembalik** [comment] 2023-08-29 18:42
@connectdotz I'll have to dig into it more because once I moved on with refactoring today, this problem disappeared. It was definitely some product of the certain test/component code. But it did happen once or twice already, so I hope next time I will be able to pin down specific bug. One thing I can add is that when the problem was appearing, the debug console didn't show anything suspicious.

Once I have more info, I'll make sure to open a new issue to report it.
