### ISSUE TITLE
All Tests are unknown and sometimes the extension fails

### ISSUE THREAD

**Issue by jahusa02** [jest-community/vscode-jest#730] opened 2021-06-17 07:33 UTC
### Environment

1. `vscode-jest version`: 4.0.3
2. `node -v`: 14.15.4
3. `npm -v` or `yarn --version`: 6.14.9
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): fhp_20_bike_api@0.1.0 C:\dev\workspace\fhp_20_bike_api
`-- jest@27.0.4
5. your vscode-jest settings if customized:
    - jest.jestCommandLine? jest
6. Operating system: Windows 10 Pro

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce

https://github.com/jahusa02/jest-extension-error

### Expected Behavior

The Jest-WS Info in the toolbar show only unknown tests. 
![grafik](https://user-images.githubusercontent.com/33373041/122351747-bec65600-cf4e-11eb-8ca6-a45f0be04890.png)

Sometimes the Watcher fails with no reason.

### Actual Behavior

Should mark the tests as successfull like so: 
![grafik](https://user-images.githubusercontent.com/33373041/122352004-fd5c1080-cf4e-11eb-8a23-1b72097bd69f.png)

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by connectdotz** [comment] 2021-06-17 21:02
hi, thanks for the repo, looks like the problem is caused by the test result json file not being generated in your environment. The extension parses this file to display the results on editors. There is a related issue already reported in jest: facebook/jest#10914 let's see if we can help them find a solution...

**Comment by rayeeroded** [comment] 2021-09-10 17:14
Having the same issue when I am using vscode with workspaces

**Comment by sazzer** [comment] 2024-02-20 07:50
I'm having the same problem. Successful test files are showing as "Unknown" and failed test files are showing as "Fail".

In particular, this means that the `testing.openTesting` setting is useless because it treats every single test run as failed regardless.

**Comment by connectdotz** [comment] 2024-02-22 22:27
@sazzer, thanks for bringing this to our attention. If the same underlying problem causes your issue, i.e., **no test result json file not being generated**, we should continue this thread (see below). Otherwise, it's best to open a new issue with details specific to your use case so we can better address it.

For the original issue:
Since this is related to the external jest issue https://github.com/jestjs/jest/issues/10914, which was closed due to no repro sample, we need a repro sample to reopen the case. Can @jahusa02 or @sazzer provide one?

**Comment by connectdotz** [comment] 2024-02-23 20:38
ok, good to know. I will close it then. 

@sazzer please feel free to reopen a new issue if you still experience something similar.

**Closed by connectdotz** 2024-02-23 20:38 UTC
Labels: external-dependency, need sample repo

**Comment by sazzer** [comment] 2024-02-23 20:42
I've tried it again and it's working correctly now. Nothing changed code wise! But maybe just a restart gave it a kick 🙂
