### ISSUE TITLE
Toggle to update coverage when tests are run

### ISSUE THREAD

**Issue by garyking** [jest-community/vscode-jest#315] opened 2018-04-27 20:28 UTC
Perhaps add a toggle so that coverage is update when test are automatically run? 

Sometimes I'm going through a coverage report, and I want to finish coverage on some parts, so I update the tests or code, then I have to manually run `yarn run test`, then refresh the coverage report.

Instead, it would be nice if the coverage reports were automatically updated when this ext runs tests (which can be toggled, since I assume creating coverage reports slows down tests a bit), then I would just have to refresh the coverage in my browser.

**Comment by seanpoulter** [comment] 2018-04-27 22:12
> Perhaps add a toggle so that coverage is update when test are automatically run?

The test coverage should update when the results change @garyking.
<br/>

Thanks for taking the time to report quite a few issues @garyking. I've noticed that have removed the template and section with "Steps to Reproduce" again. As someone who's contributing to this project in my spare time, I'd appreciate it if you kept the "Steps to Reproduce" section and **provided all the information required to to reproduce your problem.** I'd rather be spending my time investigating the issue than chasing information or guessing how to recreate the problem.

To share code with us, a repo with the minimal amount of code to reproduce the problem is appreciated. Here's an example repo from another coverage-related issue: https://github.com/seanpoulter/vscode-jest-181

**Comment by garyking** [comment] 2018-04-28 20:05
### Environment

1. `node -v`: v8.11.1
2. `npm -v`: 5.6.0
4. Operating system: macOS 10.13.3


### Steps to Reproduce



I create a HTML coverage report for my project with Jest, by setting `collectCoverage` to `true`. So whenever I run Jest myself, a coverage report is created. I then open it in my browser to view it. 

Usually there will be one or two lines that are untested in a file, and so I will either modify the code or write tests to cover those lines. Then when I want to re-check the coverage report, I have to go to Terminal and run `jest` to re-create the report. Yet the unit tests in Code are updated just fine due to this extension.


### Expected Behavior

What I'd like to see is a setting that I could add on a per-project basis, which would control whether new coverage HTML files are created every time I modify some code or tests. Although this might significantly slow down the extension if it needs to output new HTML files on every single change?

**Comment by seanpoulter** [comment] 2018-05-20 20:58
Sorry for the delay @garyking. I think you'll find these are already available now.

1.  If you configure Jest to `collectCoverage` in one of the configuration files , when it's run from the extension those coverage reports should be updated when you change things. Here's the configure I have in `jest.config.js`:

    ```js
    module.exports = {
      collectCoverage: true,
      coverageReporters: ['text', 'html', 'lcov'],
      mapCoverage: true
    }
    ```

1. There's a [`jest.showShowCoverageOnLoad`](https://github.com/jest-community/vscode-jest/blob/6d66386857c6b03664b8e9b22b43686692e9453f/package.json#L87) setting that you can add to `.vscode/settings.json` that will show the coverage report in the editor. It's not to the standard of the HTML reports that you're used to, but we'd welcome a PR that extends the default formatter.

I think those are two viable options so I'm going to close the issue. If you're having problems, feel free to reply to this issue and we can set up a video call to troubleshoot.

**Closed** 2018-05-20 20:58 UTC
Labels: bug, stage: wontfix, topic: coverage
