### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by waltercassiano** [jest-community/vscode-jest#452] opened 2019-04-25 16:39 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-jest`
- Extension Version: `2.9.2`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`Orta.vscode-jest-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jmarceli** [comment] 2019-11-28 19:47
Link doesn't work anymore. Could you update it? It looks like a duplicate of https://github.com/jest-community/vscode-jest/issues/455

**Comment by waltercassiano** [comment] 2019-12-10 14:36
Agreed, I`ll close it

**Closed** 2019-12-10 14:36 UTC
Labels: topic: performance
