### ISSUE TITLE
[FEATURE] Support native VS Code code coverage display

### ISSUE THREAD

**Issue by eliasm307** [jest-community/vscode-jest#1186] opened 2024-10-14 09:05 UTC
**Is your feature request related to a problem? Please describe.**

VS Code has some native support for showing code coverage ie https://code.visualstudio.com/docs/editor/testing#_test-coverage which allows coverage to be shown:
- in test explorer
- or inline
- or the file explorer

Currently it seems this extension has a custom implementation for showing coverage inline and with an overlay, but the native functionality would be useful also, especially the file explorer coverage which makes it easier to see overall coverage of files/folders etc

**Describe the solution you'd like**

Coverage used by the extension should also be exposed via the native VS Code coverage functionality.

**Describe alternatives you've considered**

N/A

**Additional context**

Examples of the native code coverage views:

In test explorer:

![image](https://github.com/user-attachments/assets/afd7334e-b3cf-433b-946b-6bc3620e61be)

In file explorer (with coverage per file and folder):

![image](https://github.com/user-attachments/assets/c8e1cd16-2343-49ee-ac83-0f8197f3f5c2)

VS Code API for test coverage: https://code.visualstudio.com/api/extension-guides/testing#test-coverage

**Comment by connectdotz** [comment] 2024-10-15 01:13
duplicate of #1151 

@eliasm307 this has been implemented in [pre-release v6.3.0](https://github.com/jest-community/vscode-jest/releases/tag/v6.3.0-next) ([release notes](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v6.md#v630-pre-release)).

**Comment by eliasm307** [comment] 2024-10-17 21:25
@connectdotz I've been using the re-release version of the extension and the native coverage functionality is pretty good.

My opinion is that deprecating the current custom coverage functionality or at least offering an option to turn it off (as it shows overlapping coverage with the native coverage) is a good idea.

The native coverage offers all the functionality that the current coverage does (ie gutter and in-line coverage) but in a better way.

In terms of maintenance I would imagine the native coverage would be better for you guys as you basically get features for free as the native coverage will improve over time and the vs code will cover some of the bug fixes etc and less code means less to maintain.

So generally, I'm quite happy with the native coverage functionality so far

**Comment by eliasm307** [comment] 2024-10-17 21:28
@connectdotz I've been using the re-release version of the extension and the native coverage functionality is pretty good.

My opinion is that deprecating the current custom coverage functionality or at least offering an option to turn it off (as it shows overlapping coverage with the native coverage) is a good idea.

The native coverage offers all the functionality that the current coverage does (ie gutter and in-line coverage) but in a better way.

In terms of maintenance I would imagine the native coverage would be better for you guys as you basically get features for free as the native coverage will improve over time and the vs code will cover some of the bug fixes etc and less code means less to maintain.

So generally, I'm quite happy with the native coverage functionality so far

Also regarding this issue, looks like the next version will meet my requirements so I'll close

**Closed** 2024-10-17 21:28 UTC
Labels: stage: awaiting response
