### ISSUE TITLE
How to disable annoyingly terminal pop up on launch

### ISSUE THREAD

**Issue by KevinYobeth** [jest-community/vscode-jest#973] opened 2022-12-23 03:21 UTC
### Environment

1. `vscode-jest version`: v5.1.0
2. `node -v`: v14.18.2
3. `npm -v` or `yarn --version`: 6.14.15
4. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected):  └── jest@27.5.1 
5. your vscode-jest settings if customized:
    - jest.autoRun? false
6. Operating system: Windows 11

### Prerequisite
- are you able to run jest test from the command line? yes
- how do you run your tests from the command line? (for example: `npm run test` or `node_modules/.bin/jest`) npm run test

### Steps to Reproduce

1. Open projects in vscode

### Relevant Debug Info

![image](https://user-images.githubusercontent.com/10485985/209264075-a550dab2-d2b6-4e3a-81ce-f97b74dd1e5b.png)
This is so annoying, when opening a project, it automatically start a new terminal logging the auto config. I don't want this behavior, how to disable terminal automatically popping up?

### Expected Behavior

Terminal not popping up on every launch, instead only launch when tests runner are clicked.

### Actual Behavior

Terminal annoyingly pop up on every launch.

--- 

The fastest (and the most fun) way to resolve the issue is to submit a pull-request yourself. If you are interested, feel free to check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by yunnysunny** [comment] 2022-12-23 10:02
I have set `"jest.autoRun": "off"` in my settings.json ，but it doesn't work.

**Comment by connectdotz** [comment] 2022-12-23 17:26
I think defer output till the actual run is a good idea!

**Comment by connectdotz** [comment] 2022-12-23 18:13
Here is what I am thinking for this issue:
create a new setting `jest.revealOutput: "on-run" | "silent"`
- `jest.revealOutput: "on-run"` (the default):
  - create a background terminal when the actual jest run starts
  - bring terminal to the foreground if encountered "fatal" errors that prevented jest to start, for example
- `jest.revealOutput: "silent"`: 
   - bring terminal to the foreground if encountered "fatal" errors that prevented jest to be run

clicking on the jest status bar item will always reveal and bring terminal to the foreground regardless of the setting.

Note, the silent mode could mask issues such as an unintended jest process running in the background unnoticed.

(see some explanation about background/foreground terminal [here](https://github.com/jest-community/vscode-jest/issues/854#issuecomment-1362387556))

**Comment by pot-code** [comment] 2022-12-24 03:57
They had a setting to disable it, but removed in new version.

**Comment by connectdotz** [comment] 2022-12-24 23:23
I have a prototype fix (what could be a better break for Christmas eve 🤣 ). Giving we have many enthusiastic users here, I hope you guys can help us test it:

1. unzip and install the extension patch [vscode-jest-5.1.0.vsix.zip](https://github.com/jest-community/vscode-jest/files/10299251/vscode-jest-5.1.0.vsix.zip)
2. add `"jest.revealOutput": "silent"` to your `settings.json` file
3. reload the window

Play around with it, and let me know how it works. Thanks.

**Comment by rangedsp** [comment] 2023-01-03 23:43
@connectdotz I tried the new build but the terminal is still popping up:
![image](https://user-images.githubusercontent.com/4970707/210459014-014487ae-0e42-4aa7-a261-addfabb14a78.png)

Settings:
![image](https://user-images.githubusercontent.com/4970707/210459047-a0aa4245-2ff2-4044-a559-4f333e79a774.png)
![image](https://user-images.githubusercontent.com/4970707/210459133-bfda2fa7-c96a-4bf0-9a94-20925de0a583.png)

The jest.config above is an empty file, but the terminal also pops up when I tried it in a client's project with valid jest config.

**Comment by connectdotz** [comment] 2023-01-04 03:02
@rangedsp the terminal will always be shown if there is a fatal error, such as when jest can not be started like the one above.  If there is no fatal error, the terminal should not be shown, assuming your terminal is not already opened. Let me know if you still have a problem.

**Comment by rangedsp** [comment] 2023-01-04 05:24
@connectdotz I can understand why errors prompt the terminal to show up, though in this case I am setting it to autoRun 'off' and revealOutput to be 'silence'. I.e. the intent is for jest to not do anything in the background. 

May I suggest another level of 'revealOutput' that also prevents fatal errors from showing up?

**Comment by KevinYobeth** [comment] 2023-01-04 06:45
> @connectdotz 
> May I suggest another level of 'revealOutput' that also prevents fatal errors from showing up?

I agree, there should be an option to completely disable jest terminal prompts

**Comment by connectdotz** [comment] 2023-01-04 22:20
Please help me understand why you don't want to know the fatal error if your goal is to run jest tests... 

> though in this case I am setting it to autoRun 'off' and revealOutput to be 'silence'. I.e. the intent is for jest to not do anything in the background.

When the extension starts up, before it can run jest, it will examine your environment, checking jest commands and counting test files as part of the extension setting up process. It's during this stage that it discovers the error you saw. Hiding the terminal does not stop the setup process; it only masks what really happened... 

If your environment is not ready for jest yet, maybe what you are asking is to "disable" the extension, not just the terminal?

**Comment by rangedsp** [comment] 2023-01-05 01:11
> When the extension starts up, before it can run jest, it will examine your environment, checking jest commands and counting test files as part of the extension setting up process. It's during this stage that it discovers the error you saw. Hiding the terminal does not stop the setup process; it only masks what really happened...

I have many workspaces, some with jest tests, some mainly C#, and quite a few others. That's why I turned off autoRun: I want to not know the extension jest even exists until I go into the testing tab and hit run. At that point, if a fatal error occurs it absolutely should be shown.

Yes, I do disable the extension every once in a while, but having to toggle it on/off and having to reload the window is a pain. 

This seems to be in-line with what's in the OP's 'expected behavior':

> Terminal ... only launch when tests runner are clicked.

Perhaps this is out of scope for this thread, but I'm curious to know why jest setup needs to be run on startup, as opposed to running it when you click on the testing tab? I played around with a couple of extensions I use a lot, (Docker, SQLTools, and Azure), and they only start enumerating resources when I click open their respective tabs.

**Comment by connectdotz** [comment] 2023-01-08 17:07
thanks for the feedback! 

@rangedsp 
> I have many workspaces, some with jest tests, some mainly C#, and quite a few others. That's why I turned off autoRun: I want to not know the extension jest even exists until I go into the testing tab and hit run. At that point, if a fatal error occurs it absolutely should be shown.

This pointing to the activation problem. The extension should not be activated for C# or other non-js/ts related projects. In 5.0 we switched to deep activation, which seems to bring in some unexpected mixed language dependency issues that I will look into next. I think once we resolve it, many of the apparent terminal issues would go away.

> but I'm curious to know why jest setup needs to be run on startup, as opposed to running it when you click on the testing tab? 
Users do not need to open the test tab to run tests, either automatically on startup (watch mode), or manually clicking on the editor's gutter icon. Even in manual mode, for the test files to show up in the test explorer or editor gutter status, we need to know what are the test files and parse the test files for test blocks. Therefore, there will be some setup ahead of time and there is no clear "trigger" point that we can safely delay the setup for all use cases.

@janaagaard75 
What you describe is a transient stage for the project. I can see this but thought this should happen only rarely for a given project, so shouldn't be a problem, considering the trade-off of not seeing the fatal errors... but realized that maybe others would have different preferences... 🤔 

Ok, based on all these feedbacks, I will make the following changes:
1. change the setting to `jest.autoRevealOutput: 'on-run' | 'on-fatal-error' | 'off'` 
2. need to reflect "fatal error" in the status bar, so the error is not lost even if the autoRevealOutput is "off"
3. add a new issue to investigate how to prevent mix-project activation

**Comment by connectdotz** [comment] 2023-01-08 21:31
ok, submitted the update, here is a new vsix, feel free to give it a try (note the setting name and value change, see above)

[vscode-jest-5.1.0.vsix.zip](https://github.com/jest-community/vscode-jest/files/10369539/vscode-jest-5.1.0.vsix.zip)

**Closed** 2023-01-09 23:16 UTC
Labels: enhancement

**Comment by connectdotz** [comment] 2023-01-15 23:20
Hi, the fix `jest.autoRevealOutput` is released in [5.2.0 pre-release](https://github.com/jest-community/vscode-jest/blob/master/release-notes/release-note-v5.x.md#v520-pre-release); feel free to give it a try and let us know if there is any issue.

**Comment by KevinYobeth** [comment] 2023-01-16 10:13
I've tested the pre-release version and it works flawlessly. Thank you very much @connectdotz!

**Comment by benevbright** [comment] 2023-02-24 22:28
oh Lord.. how to stop it from opening terminal popup on launch? 

```
  "jest.autoRun": "off",
  "jest.autoRevealOutput": "on-run",
```

I expect to see it only popup on my manual run, but it opens the terminal on launch.

**Comment by KevinYobeth** [comment] 2023-02-25 02:57
@benevbright change jest.autoRevealOutput to off

```
  "jest.autoRun": "off",
  "jest.autoRevealOutput": "off",
```

**Comment by EvgeniiaVak** [comment] 2023-11-10 16:50
In new version of Code Insiders there is another, more general setting setting:
```JSON
"testing.openTesting": "neverOpen"
```

**Comment by sh-pq** [comment] 2024-02-15 16:43
In case you are here because of the February 2024 update to VS Code, see this newer issue:

- https://github.com/jest-community/vscode-jest/issues/1111

The current resolution is to apply the following configuration to your preferences, [as mentioned above](https://github.com/jest-community/vscode-jest/issues/973#issuecomment-1806074551) and [by connectdotz](https://github.com/jest-community/vscode-jest/issues/1111#issuecomment-1939656073):

```json
"testing.openTesting": "neverOpen"
```
