### ISSUE TITLE
Switching branches sometimes breaks watcher

### ISSUE THREAD

**Issue by atk** [jest-community/vscode-jest#246] opened 2018-02-02 12:23 UTC
### Environment

1. `node -v`: v8.9.4
2. `npm -v`: 5.6.0
3. `npm ls react-scripts` (if you haven’t ejected): ./.

4. Operating system: Ubuntu Linux 17.04 (Zesty Zapus)

### Steps to Reproduce

Have a repository. Add one test in directory a. Create a branch. In there, add one test in directory b. Switch between branches. Watch the test watcher throw errors:

```
jest-haste-map: watch error:
  Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)...
```

### Expected Behavior

When switching branches, the watcher should be restarted (optional: only if there are changes of directories between the branches).

### Actual Behavior

Watcher process keeps on running, throwing errors as described above.

**Comment by seanpoulter** [comment] 2018-02-02 12:59
Thanks for reporting the issue @atk. It sounds like the root cause is in Jest and we should follow with them with an issue or even a PR. :wink: 

This would be a small PR if you'd like to work on building the workaround. It should be a lot easier with @marcinczenko's new process management API from PR #215.

**Comment by marcinczenko** [comment] 2018-02-02 16:01
@atk, @seanpoulter 

Indeed, we could try correct it out of the box as I am already restarting jest process when snapshots get updated.

Is there already a place where I can sense that branch has been changed. If we need to first request this from jest guys, I think we should keep it separate as I really want to get #215 merged soon so that it is easier to work on other issues.

**Closed** 2022-09-11 16:21 UTC
Labels: bug, help wanted
