### ISSUE TITLE
Failure to start jest if the project root folder contains space, eg. 'c:\work\foo and bar'

### ISSUE THREAD

**Issue by beatgates** [jest-community/vscode-jest#354] opened 2018-07-27 05:57 UTC
### Environment

1. `node -v`: 10.5.0
1. `npm -v`: 6.1.0
1. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): jest@23.4.1
1. your vscode-jest settings if customized:
    - jest.pathToJest? -
    - jest.pathToConfig? -
    - anything else that you think might be relevant? -

1. Operating system: Windows 7 Pro

### Prerequisite
- are you able to run jest test from command line? y
- how do you run your tests from command line? npm run test

### Steps to Reproduce

1. Create a project in c:\work\foo and bar
2. Create a x.test.js under  c:\work\foo and bar\test
3. Start VS Code opening folder c:\work\foo and bar

### Expected Behavior

tests start automatically

### Actual Behavior
In VS Code Terminal, you see:
'c:\work\foo' is not recognized as an internal or external command, operable program or batch file.

Starting Jest in Watch mode failed too many times and has been stopped.

**Comment by connectdotz** [comment] 2018-07-27 12:34
duplicate of #342?

**Closed** 2018-07-29 14:12 UTC
