### ISSUE TITLE
[BUG] Fails to debug tests on Windows due to issue with paths

### ISSUE THREAD

**Issue by kruncher** [jest-community/vscode-jest#1152] opened 2024-06-05 21:12 UTC
**Describe the bug**

I am seeing the following error when attempting to debug a unit test:

```
ies\\paths.test.ts ogram\ Files\\nodejs\\npm.cmd test -- --runInBand --watchAll=false --testNamePattern discoverFilesRecursively\\\(\\\)\ discovers\ all\ files\ with\ one\ file\ extension\$ --runTestsByPath C:\\Users\\me\\Desktop\\minimal-ts\\utiliti
633;C'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Some useful points:
- The tests run properly from the command line.
- The extension is able to run tests fine.
- The extension shows the pass/fail icons as appropriate.
- It is only the "Debug Test" feature which is not working.

**To Reproduce**
1. Go to the unit test file.
2. Right-click on the green check icon to the left of the unit test.
3. Select 'Debug Test'.

**Expected behavior**
Unit test should run and should break at breakpoint.

**Environment (please complete the following information):**
- vscode-jest version:6.2.5
- `node -v`: 22.2.0
- `npm -v` or `yarn --version`: 10.7.0
- jest or react-scripts (if you haven’t ejected) version: 29.7.0
- your vscode-jest settings:
    ```json
    "jest.shell": "",
    "jest.runMode": null,
    "jest.coverageColors": null
    ```
- Operating system: Windows 10

**Prerequisite**
- are you able to run jest from the command line? yes
- where do you run jest CLI from? root directory of the project
- how do you run your tests from the command line? "npm run test"

**Comment by connectdotz** [comment] 2024-06-15 20:32
hi the command line didn't seem to be complete. Please repaste the full command line; and your debug config for jest if you have a customized one.

**Comment by olifer** [comment] 2024-06-20 09:14
I've encountered a similar issue on Windows due to the generated configuration by default. Try to define your test config in `.vscode/launch.json` as mentioned in these [docs](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest#debug-config-v2):

```json
{
  "type": "node",
  "name": "vscode-jest-tests.v2",
  "request": "launch",
  "program": "${workspaceFolder}/node_modules/.bin/jest",
  "args": [
    "--runInBand",
    "--watchAll=false",
    "--testNamePattern",
    "${jest.testNamePattern}",
    "--runTestsByPath",
    "${jest.testFile}"
  ],
  "cwd": "${workspaceFolder}",
  "console": "integratedTerminal",
  "internalConsoleOptions": "neverOpen",
  "disableOptimisticBPs": true,
  "windows": {
    "program": "${workspaceFolder}/node_modules/jest/bin/jest"
  }
}
```

Notice that the `name` is important here, if it does not start with `vscode-jest-tests.v2` the default config will be generated.

**Comment by davidcoleman007** [comment] 2024-07-24 18:23
@olifer this does not solve the problem.

I have also followed these steps, but they were not necessary in the first place as the command line is being generated fine without customizing the config.

the issue is that the generated command line is missing quotes around the "npm.cmd" path.

Please see here:
![image](https://github.com/user-attachments/assets/fef42d6e-4e73-44ef-ac33-211f9ddd6cbe)

**Comment by davidcoleman007** [comment] 2024-07-24 18:55
also, i would ask, how can we replace the usage of "{npm cmd line} test" with something more generic such as "npx jest". Not all projects have a "test" script that is suitable for this purpose. In our case, for many (maybe wrong but beyond my power to change) reasons, our "test" script also runs linting and a number of other unnecessary steps, which make it not suitable for use as the debug test runner.

**Comment by davidcoleman007** [comment] 2024-07-31 18:22
@connectdotz Just following up on this. Is there further information that can help us find a resolution?

**Comment by connectdotz** [comment] 2024-08-02 20:04
@davidcoleman007 I have a few suggestions:

1. If you are on Windows, try using the `"windows"` config as @olifer mentioned.
2. You don't need to use `npm test`. If you want to run `npx jest`, you can change the config accordingly.

For example, you can try something like this:
```json
{
  "type": "node",
  "name": "vscode-jest-tests.v2.{reponame}",
  "request": "launch",
  "args": [
    "jest",
    "--",
    "--runInBand",
    "--watchAll=false",
    "--testNamePattern",
    "${jest.testNamePattern}",
    "--runTestsByPath",
    "${jest.testFile}"
  ],
  "cwd": "c:\\code\\{reponame}",
  "console": "integratedTerminal",
  "internalConsoleOptions": "neverOpen",
  "disableOptimisticBPs": true,
  "windows": {
    "runtimeExecutable": "npx" 
  }
}

As you can see, you have full control over what command the debugger should launch with. The extension only substitutes the variables in the config, such as ${jest.testNamePattern}; it doesn't impose any additional constraints. Feel free to experiment (like adding quotes or the full path of the program if VSCode didn't spawn the right command line), and let us know if you have any additional questions.

**Comment by stefanone91** [comment] 2024-08-06 14:28
I've resolved simply by calling  directly jest from node modules instead of passing through npm.
This is my launch.json config:

```json
{
            "type": "node",
            "name": "vscode-jest-tests.v2.{PROJECT_NAME}", // Adapt this
            "request": "launch",
            "args": [ 
                // Removed first two params from the command
                "--runInBand",
                "--watchAll=false",
                "--testNamePattern",
                "${jest.testNamePattern}",
                "--runTestsByPath",
                "${jest.testFile}"
            ],
            "cwd": "${workspaceRoot}",
            "console": "integratedTerminal",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/jest", // Changed this
}
```

**Comment by connectdotz** [comment] 2024-08-08 19:22
Great! Yes, the debug configuration in VSCode is quite flexible—kudos to the team for that. I encourage everyone to experiment with it; you should be able to find a solution that works for your project.

Since no further action is required from the extension, I’ll go ahead and close this issue.

**Closed by connectdotz** 2024-08-08 19:22 UTC
Labels: stage: awaiting response
