### ISSUE TITLE
coverage overlay is not visible

### ISSUE THREAD

**Issue by phra** [jest-community/vscode-jest#320] opened 2018-05-03 08:28 UTC
### Environment

1. `node -v`: 9.11.1
2. `npm -v`: 5.6.0

4. Operating system: Debian

![image](https://user-images.githubusercontent.com/984628/39566649-98c39a32-4ebc-11e8-92f0-b5e39a9f02aa.png)

### Steps to Reproduce

1. clone https://github.com/seanpoulter/vscode-jest-181
2. open vscode

### Expected Behavior

coverage overlay is visible in the editor.

### Actual Behavior

coverage overlay is not visible.

![image](https://user-images.githubusercontent.com/984628/39566641-92da5750-4ebc-11e8-841c-34cc7dc3cb39.png)

**Comment by seanpoulter** [comment] 2018-05-04 18:26
Does anyone have time to debug the extension? I'd suggest breakpoints [here](https://github.com/jest-community/vscode-jest/blob/7964a9d6c675502f8e3f080a3335c975a0908e63/src/JestExt.ts#L225) and [here](https://github.com/jest-community/vscode-jest/blob/7964a9d6c675502f8e3f080a3335c975a0908e63/src/JestExt.ts#L381).

**Comment by ThomasRooney** [comment] 2018-05-12 01:34
@seanpoulter @phra -- I spent a few hours and worked it out after this bugged me today -- both the lack of markers and the annoyance that the red line is in the wrong place.

Its because the jest executable isn't switched based on OS, so windows fails when it tries to run the shell script (instead of the 'cmd' file). The markers are due to using a hardcoded 0 => 6 column definition in the 'diagnoses' visual studio code API, instead of using the 'whole line' equivalent.

**Comment by ArsProgramma** [comment] 2018-05-13 19:15
works perfectly now. Thanks!

**Comment by phra** [comment] 2018-05-14 08:29
@ThomasRooney @ArsProgramma i don't see it working on linux yet. do i have to do something in particular beside toggling the coverage via the menu?

![image](https://user-images.githubusercontent.com/984628/39986283-8744f6ae-5761-11e8-9dd3-073d3ce5636b.png)

**Comment by seanpoulter** [comment] 2018-05-20 01:12
Are you still having problems @phra? I can't reproduce the issue from OSX or Windows 7 on that example repo from Issue 181. Is your repo above [configured to collect code coverage](https://github.com/jest-community/vscode-jest#how-do-i-show-code-coverage)? If you clone the extension repo I'm happy to help debug the problem(s). It's a good chance to try the [Live Share](https://code.visualstudio.com/blogs/2017/11/15/live-share) to remote pair.

**Comment by phra** [comment] 2018-05-20 02:27
i'm still not able to see the overlay.. i will try to debug it this weekend.

**Comment by seanpoulter** [comment] 2018-05-21 02:28
Let me know if you need a hand. I'm going to close this since I've been able to see the code coverage on an Ubuntu image using the example repo - https://github.com/seanpoulter/vscode-jest-181.

**Closed by seanpoulter** 2018-05-21 02:28 UTC
Labels: bug, stage: awaiting response, topic: coverage
