### ISSUE TITLE
Backticks makes gui hang.

### ISSUE THREAD

**Issue by H-a-w-k** [jest-community/vscode-jest#384] opened 2018-09-29 13:28 UTC
it(`checking jest`, () => {
});

Tests work, but vscode green/red circle does not. Hangs on empty circle waiting for changes.

**Comment by connectdotz** [comment] 2018-10-10 02:17
this is a known issue, the current test parser doesn't handle templateLiteral (backtick) yet, I am working on a parser PR that will include this fix.

**Comment by connectdotz** [comment] 2018-10-19 05:15
duplicate of #247

**Closed by connectdotz** 2018-10-19 05:15 UTC
Labels: duplicate, stage: in progress
