### ISSUE TITLE
[BUG] Not able to run test more than once

### ISSUE THREAD

**Issue by hkan0157** [jest-community/vscode-jest#1124] opened 2024-03-06 06:07 UTC
**Describe the bug**
I'm able to run only once in VS Code using Jest extension. In order to test it again, If I run the same test it just loads for long time, nothing happens. I need to close and open each time to run tests. But when I run tests as debug, it is fine. But when we need to run as normal test it doesn't allow.

**Environment (please complete the following information):**
- vscode-jest version:[1.87.0]
- `node -v`: [v14.20.0]
- `npm -v` or `yarn --version`: [npm 6.14.17]
- your vscode-jest settings:
    "jest.runMode": "on-demand",
    "jest.debugMode": true
    - anything else that you think might be relevant? [e.g., none]
- Operating system: [e.g., Windows 10 Enterprise]

**Prerequisite**
- are you able to run jest from the command line? Not sure
- where do you run jest CLI from? [root directory of the project]
- how do you run your tests from the command line? (Using Jest extension) 

---

The fastest (and the most fun) way to resolve the issue is to submit a pull request yourself. If you are interested, please check out the [contribution guide](https://github.com/jest-community/vscode-jest/CONTRIBUTING.md), we look forward to seeing your PR...

**Comment by maxpatiiuk** [comment] 2024-03-10 16:12
I'm having the exact same issue - the test/tests show up as running, but nothing happens (and the 1min timeout is not triggered either)

https://github.com/jest-community/vscode-jest/assets/40512816/1b1e718f-72fb-4624-a501-77a551d86dba


I am in a monorepo with virtual folders setup and a custom Jest command. Settings:

```json
{
  "jest.jestCommandLine": "yarn test",
  "jest.virtualFolders": [
    { "name": "components-controllers", "rootPath": "packages/support-packages/components-controllers" }
  ],
  "jest.runMode": "on-demand",
  "jest.debugMode": true,
}
```

Where `yarn jest` is defined as `stencil test --spec --` (Stencil is proxying all extra flags to Jest CLI)

---

are you able to run jest from the command line? Yes
where do you run jest CLI from? rootPath is set to `packages/support-packages/components-controllers`
how do you run your tests from the command line? Using Stencil, which wraps over Jest and forwards the arguments

---

If I change the jest.debugMode from true to false or the other direction, a window with this error pops up:
![Screenshot 2024-03-10 at 09 06 56](https://github.com/jest-community/vscode-jest/assets/40512816/e9666d0a-07fa-4faf-943f-7f67eac47336)

Sometimes I also see `[error] failed to schedule test for /Users/mak13180/site/esri/arcgis-web-components-migration/packages/support-packages/components-controllers/src`

**Comment by connectdotz** [comment] 2024-03-11 03:15
Hmm... do you guys have a sample repo I can try to repro?

**Comment by maxpatiiuk** [comment] 2024-03-11 03:22
reload/restart does not fix the issue (happens again after the first run)
when tests auto-run as part of creating new file or saving changes, all works fine
when debugging individual test, all works fine
it's only when running individual test in non-debug mode that it never completes - and such uncompleted tests are not stoppable/cancellable either

> Does this happen all the time or just occasionally?

happens consistently in the condition described above. and consistently does not happen in the other conditions

> do you guys have a sample repo I can try to repro?

I will try to create one tomorrow and will post the link here (might take a bit of time as the bug happens in a large proprietary monorepo)

**Comment by maxpatiiuk** [comment] 2024-03-11 20:43
I pushed a minimum reproducible case in this repo - https://github.com/maxpatiiuk/vscode-jest-bug-reproduction

README.md contains reproduction steps

This might have something to do with Yarn, as changing run command from `yarn test` to `npm run test` resolves the issue

**Comment by connectdotz** [comment] 2024-03-15 22:44
@maxpatiiuk, thanks for the sample repo. I can now reproduce this issue. It seems that the process we spawned was never closed as expected, thus blocking the subsequent test request.

The issue seems to be related to `stencil`, not yarn. If I run jest directly (by not setting jest.jestCommandLine), everything worked as expected. Looking at the command line we generated, the culprit seems to be the `"--watchAll=false", stencil interpreted this incorrectly and started the process in watch mode, opposite of what we intended. 

You can easily reproduce this by issuing this command in the terminal: 
```sh
yarn test --listTests --json --watchAll=false
``` 
You will see it went into a watch mode. Now compare with running jest directly: 
```sh
yarn jest --listTests --json --watchAll=false
```
Directly running jest shows the right behavior. You might want to file a bug report in stencil.

**Comment by connectdotz** [comment] 2024-03-15 22:46
@hkan0157, not sure if you have the same stencil dependency. I noticed your node/npm version is really old. The latest jest doesn't even support those versions anymore... which jest version you are running?

**Closed** 2024-04-05 21:35 UTC
Labels: bug, enhancement, stage: awaiting response, external-issue
